spring.application.name: long-polling

spring:
  config:
    import:
      - application-core.yml
      - application-common.yml

server:
  port: 8082
  servlet:
    context-path: /long-polling
  shutdown: graceful