spring.application.name: socket

spring:
  config:
    import:
      - application-core.yml
      - application-common.yml

server:
  port: 8085
  servlet:
    context-path: /socket
  shutdown: graceful